---
AWSTemplateFormatVersion: '2010-09-09'

# Any code, applications, scripts, templates, proofs of concept,
# documentation and other items are provided for illustration purposes only.
#
# Copyright 2017 Amazon Web Services
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Parameters:
  Tag:
    Type: String

  TaskName:
    Type: String

  DesiredCount:
    Type: Number
    Default: 0

  LoadBalancerListenerArn:
    Type: String
    MinLength: 1
    MaxLength: 255
    Description: "ALB Listener ARN"

  EcsClusterName:
    Type: String
    MinLength: 1
    MaxLength: 255
    Description: "ECS cluster name"

  CiRepositoryName:
    Type: String
    MinLength: 1
    MaxLength: 255
    Description: "CI/CD repository name"

  VpcId:
    Type: String
    MinLength: 1
    MaxLength: 255
    Description: "VPC stack name"

  TargetGroupArn:
    Type: String
    MinLength: 1
    MaxLength: 255
    Description: "Target group arn"

  DeploymentPipelineStackName:
    Type: String
    MinLength: 1
    MaxLength: 255
    Description: "Deployment pipeline stack name"

Resources:

  EcsServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "ecs.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole

  Service:
    Type: "AWS::ECS::Service"
    Properties:
      Cluster: !Ref EcsClusterName
      Role: !Ref EcsServiceRole
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: !Ref TaskName
          ContainerPort: 80
          TargetGroupArn: !Ref TargetGroupArn
    DependsOn:
      - TaskDefinition

  TaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Family: !Sub "${AWS::StackName}-${TaskName}"
      ContainerDefinitions:
        - Name: !Ref TaskName
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${CiRepositoryName}:${Tag}"
          Essential: true
          Memory: 128
          PortMappings:
            - ContainerPort: 80
          Environment:
            - Name: Tag
              Value: !Ref Tag

  EcsContainerDiedEventRule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: !Sub "EcsContainerDiedEventRule-${AWS::StackName}"
      EventPattern:
        source:
          - "aws.ecs"
        detail-type:
          - "ECS Task State Change"
        detail:
          stoppedReason:
            - "Essential container in task exited"
          lastStatus:
            - "STOPPED"
          desiredStatus:
            - "STOPPED"
          taskDefinitionArn:
            - !Ref TaskDefinition
      State: "ENABLED"
      Targets:
        - Arn:
            Fn::ImportValue: !Sub "${DeploymentPipelineStackName}-ecs-container-died-topic-arn"
          Id: !Sub "ecs-container-died-target-${AWS::StackName}"
    DependsOn:
      - TaskDefinition

Outputs:

  # TODO: Do we need the TaskName here too?

  ServiceArn:
    Value: !Ref Service
    Export:
      Name: !Sub "${AWS::StackName}-${TaskName}-service-arn"

  ServiceName:
    Value: !GetAtt Service.Name
    Export:
      Name: !Sub "${AWS::StackName}-${TaskName}-service-name"

  TaskDefinitionArn:
    Value: !Ref TaskDefinition
    Export:
      Name: !Sub "${AWS::StackName}-${TaskName}-task-definition-arn"


